name: Build and Run Automated Tests
# This workflow is triggered on pushes to the repository.
on: push

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: false
      matrix:
        name: [clang, gcc]
        include:
          - name: clang
            cc: clang
            cxx: clang++

          - name: gcc
            cc: gcc
            cxx: g++

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ clang libgtest-dev
          sudo apt-get install -y ninja-build  # Optional but speeds up builds

      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build .

      - name: Run tests
        run: cd ./bin && ./testing

  linter:
    name: linter
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - uses: actions/checkout@v4

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format clang-tidy

      - name: Set run permissions
        run: chmod +x .github/workflows/linter.sh

      - name: Run the linter
        run: .github/workflows/linter.sh